name: "IntegriMark Mailing"
description: "Send emails with watermarking links using IntegriMark"
branding:
  icon: "mail"
  color: "blue"

# on:
#   workflow_dispatch:
#   schedule:
#     - cron: '0 0 * * *'  # Scheduled to run daily at midnight

inputs:
  sendgrid_api_key:
    description: "SendGrid API Key."
    required: false
  smtp_server:
    description: "SMTP server address."
    required: false
  smtp_port:
    description: "SMTP server port."
    required: false
  smtp_username:
    description: "SMTP username."
    required: false
  smtp_password:
    description: "SMTP password."
    required: false
  from_email:
    description: "From email address."
    required: true
  csv_input_file:
    description: "Path to a CSV file to use as input."
    required: false
  google_spreadsheet_id:
    description: "Google Spreadsheet ID."
    required: false
  google_worksheet_index:
    description: "Worksheet index in the spreadsheet."
    required: false
  service_account_json_path:
    description: "Path to the service_account.json file to access Google's API."
    required: false
  email_column:
    description: "Column name or index for email addresses."
    required: true
  files_column:
    description: "Column name or index for files."
    required: false
  passwords:
    description: "Path to the passwords.json file."
    required: false
    default: "passwords.json"
  template_file:
    description: "Path to a custom email template file."
    required: false
  email_status_file:
    description: "Path to the email status JSON file."
    required: false
    default: "email-status.json"
  no_send_mode:
    description: "Flag to run in no-send mode."
    required: false
    default: "false"

jobs:
  send_emails:
    runs-on: ubuntu-latest
    steps:
      - name: "📥 Checkout Repository"
        uses: actions/checkout@v2

      - name: "🐍 Set up Python"
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: "📦 Install IntegriMark"
        run: |
          python -m pip install --upgrade pip setuptools
          pip install integrimark
        shell: bash

      - name: "🔍 Validate Inputs"
        run: python validate_input_and_invoke_integrimark.py
        env:
          SENDGRID_API_KEY: ${{ inputs.sendgrid_api_key }}
          SERVICE_ACCOUNT_JSON: ${{ inputs.service_account_json_path }}
          SMTP_SERVER: ${{ inputs.smtp_server }}
          SMTP_PORT: ${{ inputs.smtp_port }}
          SMTP_USERNAME: ${{ inputs.smtp_username }}
          SMTP_PASSWORD: ${{ inputs.smtp_password }}
          FROM_EMAIL: ${{ inputs.from_email }}
          CSV_INPUT_FILE: ${{ inputs.csv_input_file }}
          GOOGLE_SPREADSHEET_ID: ${{ inputs.google_spreadsheet_id }}
          GOOGLE_WORKSHEET_INDEX: ${{ inputs.google_worksheet_index }}
          EMAIL_COLUMN: ${{ inputs.email_column }}
          FILES_COLUMN: ${{ inputs.files_column }}
          PASSWORDS: ${{ inputs.passwords }}
          TEMPLATE_FILE: ${{ inputs.template_file }}
          EMAIL_STATUS_FILE: ${{ inputs.email_status_file }}
          NO_SEND_MODE: ${{ inputs.no_send_mode }}

      - name: "📝 Commit Email Status File"
        if: success()
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add ${{ inputs.email_status_file }}
          git commit -m "Update email status file"
          git push
        shell: bash
